# Generated by Django 2.2.4 on 2020-01-06 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('info', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('package_city_routes', models.CharField(max_length=500)),
                ('itinerary', models.TextField()),
                ('inclusion', models.TextField()),
                ('exclusion', models.TextField()),
                ('policy_and_terms', models.TextField()),
                ('images', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baseApp.Category')),
            ],
        ),
    ]
