# Generated by Django 2.2.4 on 2020-01-11 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0003_tripcomments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('package_city_routes', models.CharField(max_length=500)),
                ('itinerary', models.TextField()),
                ('inclusion', models.TextField()),
                ('exclusion', models.TextField()),
                ('policy_and_terms', models.TextField()),
                ('images', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TourPackages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('info', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='info',
        ),
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.AddField(
            model_name='packages',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='baseApp.Category'),
        ),
        migrations.AddField(
            model_name='packages',
            name='tour_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='baseApp.TourPackages'),
        ),
    ]
