# Generated by Django 2.2.4 on 2020-01-12 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0005_auto_20200112_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baseApp.Packages')),
            ],
        ),
    ]
