# Generated by Django 2.2.4 on 2020-01-12 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0006_packagequery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagequery',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='baseApp.Packages'),
        ),
    ]
