# Generated by Django 2.2.4 on 2020-01-13 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0007_auto_20200112_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('added_date', models.DateField(default=datetime.datetime.now)),
                ('content', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='blog_images')),
            ],
        ),
    ]
