# Generated by Django 2.2.4 on 2020-01-13 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0008_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='added_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images'),
        ),
    ]
